### ISSUE TITLE
Rename default "master" branch to "main"

### ISSUE THREAD

**Issue by fnogatz** [AndreasMadsen/interpreted#12]
Hey @AndreasMadsen, thank you for adding me as maintainer in https://github.com/AndreasMadsen/interpreted/pull/10#issuecomment-1099210476. I would like to rename the project's default branch `master` to `main`, following Git's defaults. A brief summary of the recent developments regarding the shift towards `main` instead of `master` is given in these articles of [GitLab](https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/) and [GitHub](https://github.com/github/renaming). However, I don't have permission to rename the project's default branch. Any chances we can change this?

**Comment by AndreasMadsen** [comment]
done
