### ISSUE TITLE
Adding interpreted as dependency crashes `npm audit`

### ISSUE THREAD

**Issue by fnogatz** [AndreasMadsen/interpreted#9]
I use *interpreted* in [xsd2json](https://github.com/fnogatz/xsd2json). It fails to run `npm audit`, apparently because of *interpreted*, which is added as a devDependency. It seems that even this minimal package.json fails to run `npm audit`:

```sh
> cat package.json
{
  "name": "test-interpreted",
  "version": "1.0.0",
  "dependencies": {
    "interpreted": "^1.0.1"
  }
}
> npm audit
npm ERR! code ENOAUDIT
npm ERR! audit Your configured registry (https://registry.npmjs.org/) may not support audit requests, or the audit endpoint may be temporarily unavailable.
npm ERR! audit The server said: Invalid package tree, run  npm install  to rebuild your package-lock.json
```

Do you have more luck running `npm audit`?

If this fails for you, too, I could have a more detailed look into it.

**Comment by AndreasMadsen** [comment]
I can reproduce the error.

**Comment by fnogatz** [comment]
It is working again, so it might have been an issue with npm or the TAP package. However, this issue can be closed.
